version: 1.0.{build}
build: off
test: off
artifacts:
- path: 'details.html'
  type: WebDeployPackage
- path: 'donations.html'
  type: WebDeployPackage
- path: 'downloads.html'
  type: WebDeployPackage
- path: 'faqs.html'
  type: WebDeployPackage
- path: 'errors.html'
  type: WebDeployPackage
- path: 'index.html'
  type: WebDeployPackage
- path: 'license.html'
  type: WebDeployPackage
deploy:
- provider: FTP
  host: ftp.movie-file-merger.org
  protocol: ftp
  username: movie-file-merger.org
  password:
    secure: Zp8Gcw4ltIVgECijdag2AA==
    version: 1.0.{build}